In [2]:
%load_ext autoreload
%autoreload 2

import pandas as pd
import datetime
import numpy as np
import os
from acoustic_data_science import config, helpers
import matplotlib.pyplot as plt

[array([ 0.5,  0.5,  0.5, ..., 24. ,  2. ,  0.5]),
 array([188. ,   0.5,   1.5, ...,   1. ,   0.5,   0.5]),
 array([ 1. ,  0.5,  0.5, ..., 28. , 28. , 20.5]),
 array([37.5, 37.5,  0.5, ...,  0.5,  0.5, 13.5]),
 array([29.5,  0.5,  0.5, ...,  0.5,  6.5, 36.5]),
 array([24. , 63. ,  1.5, ...,  0.5,  0.5,  1. ]),
 array([ 1. ,  0.5,  0.5, ..., 16.5,  1.5,  0.5]),
 array([0.5, 0.5, 0.5, ..., 0.5, 0.5, 5. ]),
 array([0.5, 0.5, 0.5, ..., 0.5, 0.5, 0.5]),
 array([ 0.5,  0.5,  0.5, ...,  0.5,  2. , 31. ])]